name: Execute Commands

on:
  push:
    branches:
      - master

jobs:
  execute-commands:
    runs-on: ubuntu-latest
    env:
      DOLT_PORTAL: ${{ secrets.dolt_portal }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Access GitHub Secret
        run: |
          echo "GitHub Secret Value: $DOLT_PORTAL"
